#install: gradle wrapper --gradle-version 5.1.1
env:
  global:
    - CC_TEST_REPORTER_ID=8b9d78a19bed1ccf125d32a07fcbf455c5d887e45ac0bf5d5e74c0fe2c647831
install: ./gradlew assemble
language: java
jdk:
  - oraclejdk8
  - openjdk8

before_script:
    - chmod a+x gradlew

script:
  - ./gradlew build check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)





