#install: gradle wrapper --gradle-version 5.1.1
env:
  global:
    - CC_TEST_REPORTER_ID=8b9d78a19bed1ccf125d32a07fcbf455c5d887e45ac0bf5d5e74c0fe2c647831
install: ./gradlew assemble
language: java
jdk:
  - oraclejdk8
  - openjdk8

before_script:
  - chmod a+x gradlew
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./gradlew build

after_script:
  - ./cc-test-reporter format-coverage --debug JACOCO_SOURCE_PATH=src/main/java/io/alkal/kalium ./cc-test-reporter \
  --input-type jacoco --exit-code $TRAVIS_TEST_RESULT
  
  - ./cc-test-reporter upload-coverage





